"""AlAll Changes done

Revision ID: 30e556a480f5
Revises: c9c133ad5eaf
Create Date: 2024-01-18 11:11:59.808692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e556a480f5'
down_revision = 'c9c133ad5eaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
